# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-22 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0006_case_ip_network")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="as_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="as_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
