# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0007_add_as_number")]

    operations = [
        migrations.AddField(
            model_name="case",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="event",
            name="country_code",
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
