# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0008_add_country_code")]

    operations = [
        migrations.AlterModelOptions(
            name="case", options={"ordering": ("start_date",)}
        ),
        migrations.AlterModelOptions(name="event", options={"ordering": ("date",)}),
    ]
