# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_case_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='netmask',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
