language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
branches:
  only:
  - master
env:
  global:
    - DJANGO_SECRET_KEY=secret
    - PIP_UPGRADE=no
  matrix:
    - DJANGO_VERSION=">=2.2,<3.0"
    - DJANGO_VERSION=">=3.0,<3.1"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgeoip-dev
install:
  - pip install "django${DJANGO_VERSION}"
script:
  - make test
