language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
env:
  global:
    - DJANGO_SECRET_KEY=secret
    - PIP_UPGRADE=no
  matrix:
    - DJANGO_VERSION=">=2.0,<2.1"
    - DJANGO_VERSION=">=2.1,<2.2"
    - DJANGO_VERSION=">=2.2,<3.0"
    - DJANGO_VERSION=">=3.0,<3.1"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgeoip-dev
install:
  - pip install --upgrade pytest
  - pip install "django${DJANGO_VERSION}"
  - make requirements/development.txt.done
script:
  - make test
