language: python
cache: pip
python:
  - 3.4
  - 3.5
  - 3.6
env:
  global:
    - DJANGO_SECRET_KEY=secret
  matrix:
    - DJANGO_VERSION=1.8.17
    - DJANGO_VERSION=1.9.12
    - DJANGO_VERSION=1.10.6
    - DRF_VERSION=3.6.1
    - DRF_VERSION=3.5.4
    - DRF_VERSION=3.4.7
install:
  - pip install django==$DJANGO_VERSION djangorestframework=$DRF_VERSION
  - make requirements/development.txt.done
script:
  - make test
