# Generated by Django 2.2.9 on 2019-12-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CaseRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement", models.CharField(max_length=32)),
                ("requirement_param", models.CharField(max_length=32)),
                ("action", models.CharField(max_length=32)),
                (
                    "action_kwargs",
                    models.CharField(blank=True, default="", max_length=256),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="EventRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement", models.CharField(max_length=32)),
                ("requirement_param", models.CharField(max_length=32)),
                ("action", models.CharField(max_length=32)),
                (
                    "action_kwargs",
                    models.CharField(blank=True, default="", max_length=256),
                ),
            ],
            options={"abstract": False},
        ),
    ]
